from app.schemas.common import APIResponse, PaginatedResponse, GeoBoundingBox, GeoLocation
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserLogin,
    UserUpdate,
    UserResponse,
    Token,
    TokenPayload,
    VendorProfileCreate,
    VendorProfileResponse,
)
from app.schemas.guide import (
    LocalGuideBase,
    LocalGuideCreate,
    LocalGuideSummary,
    LocalGuideDetail,
    GuideAvailabilityResponse,
)
from app.schemas.room import (
    RoomTypeBase,
    RoomTypeCreate,
    RoomTypeResponse,
    RoomAllocationCreate,
    RoomAllocationBatchCreate,
    RoomAllocationResponse,
)
from app.schemas.property import (
    PropertyBase,
    PropertyCreate,
    HotelSearchParams,
    HotelCardResponse,
    ResortSearchParams,
    ResortCardResponse,
    PropertyDetailResponse,
)
from app.schemas.booking import (
    RoomBookingItemRequest,
    GuideBookingItemRequest,
    ReservationCreateRequest,
    PriceQuoteRequest,
    PriceQuoteResponse,
    RoomBookingItemResponse,
    GuideBookingItemResponse,
    ReservationResponse,
)
from app.schemas.review import ReviewCreate, ReviewResponse

__all__ = [
    "APIResponse",
    "PaginatedResponse",
    "GeoBoundingBox",
    "GeoLocation",
    "UserBase",
    "UserCreate",
    "UserLogin",
    "UserUpdate",
    "UserResponse",
    "Token",
    "TokenPayload",
    "VendorProfileCreate",
    "VendorProfileResponse",
    "LocalGuideBase",
    "LocalGuideCreate",
    "LocalGuideSummary",
    "LocalGuideDetail",
    "GuideAvailabilityResponse",
    "RoomTypeBase",
    "RoomTypeCreate",
    "RoomTypeResponse",
    "RoomAllocationCreate",
    "RoomAllocationBatchCreate",
    "RoomAllocationResponse",
    "PropertyBase",
    "PropertyCreate",
    "HotelSearchParams",
    "HotelCardResponse",
    "ResortSearchParams",
    "ResortCardResponse",
    "PropertyDetailResponse",
    "RoomBookingItemRequest",
    "GuideBookingItemRequest",
    "ReservationCreateRequest",
    "PriceQuoteRequest",
    "PriceQuoteResponse",
    "RoomBookingItemResponse",
    "GuideBookingItemResponse",
    "ReservationResponse",
    "ReviewCreate",
    "ReviewResponse",
]
